import json
import math
import subprocess
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
USERNAME = "isikawatatsuki"


def github_api(*args):
    result = subprocess.run(
        ["gh", "api", *args],
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return json.loads(result.stdout)


def escape(value):
    return str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def text(x, y, value, size=18, color="#f8fafc", weight=400, anchor="start"):
    return (
        f'<text x="{x}" y="{y}" font-size="{size}" fill="{color}" '
        f'font-weight="{weight}" text-anchor="{anchor}">{escape(value)}</text>'
    )


query = """
query($login:String!) {
  user(login:$login) {
    followers { totalCount }
    following { totalCount }
    repositories(first:100, ownerAffiliations:OWNER, privacy:PUBLIC) {
      totalCount
      nodes {
        stargazerCount
        forkCount
        languages(first:10) { edges { size node { name color } } }
      }
    }
    contributionsCollection {
      totalCommitContributions
      totalIssueContributions
      totalPullRequestContributions
      totalPullRequestReviewContributions
      contributionCalendar { totalContributions }
    }
  }
}
"""

user = github_api("graphql", "-F", f"login={USERNAME}", "-f", f"query={query}")["data"]["user"]
repos = user["repositories"]
contributions = user["contributionsCollection"]
stars = sum(repo["stargazerCount"] for repo in repos["nodes"])
forks = sum(repo["forkCount"] for repo in repos["nodes"])

languages = Counter()
language_colors = {}
for repo in repos["nodes"]:
    for edge in repo["languages"]["edges"]:
        name = edge["node"]["name"]
        languages[name] += edge["size"]
        language_colors[name] = edge["node"].get("color") or "#e95420"

common_style = (
    '<defs><linearGradient id="surface" x1="0" y1="0" x2="1" y2="1">'
    '<stop stop-color="#2c001e"/><stop offset="1" stop-color="#451337"/>'
    '</linearGradient></defs>'
)

stats = [
    ("Repositories", repos["totalCount"]),
    ("Commits", contributions["totalCommitContributions"]),
    ("Pull requests", contributions["totalPullRequestContributions"]),
    ("Issues", contributions["totalIssueContributions"]),
    ("Reviews", contributions["totalPullRequestReviewContributions"]),
    ("Contributions", contributions["contributionCalendar"]["totalContributions"]),
    ("Stars", stars),
    ("Forks", forks),
    ("Followers", user["followers"]["totalCount"]),
    ("Following", user["following"]["totalCount"]),
]

stats_svg = [
    '<svg xmlns="http://www.w3.org/2000/svg" width="900" height="300" viewBox="0 0 900 300" '
    'style="font-family:Ubuntu Mono,DejaVu Sans Mono,monospace">',
    common_style,
    '<rect x="1" y="1" width="898" height="298" rx="12" fill="url(#surface)" stroke="#e95420" stroke-width="2"/>',
    text(34, 48, "$ github-stats --live", 23, "#e95420", 700),
    text(34, 76, "Live data generated by GitHub Actions", 14, "#d8b4c8"),
]
for index, (label, value) in enumerate(stats):
    column = index // 5
    row = index % 5
    x = 34 + column * 440
    y = 116 + row * 34
    stats_svg += [
        text(x, y, label, 17, "#f8fafc"),
        text(x + 382, y, value, 18, "#67e8f9", 700, "end"),
    ]
stats_svg.append("</svg>")

top_languages = languages.most_common(8)
total_bytes = sum(size for _, size in top_languages) or 1
language_svg = [
    '<svg xmlns="http://www.w3.org/2000/svg" width="900" height="380" viewBox="0 0 900 380" '
    'style="font-family:Ubuntu Mono,DejaVu Sans Mono,monospace">',
    common_style,
    '<rect x="1" y="1" width="898" height="378" rx="12" fill="url(#surface)" stroke="#e95420" stroke-width="2"/>',
    text(34, 48, "$ language-stats --graph", 23, "#e95420", 700),
    text(34, 76, "Public repositories · bytes by language", 14, "#d8b4c8"),
]
for index, (name, size) in enumerate(top_languages):
    y = 112 + index * 32
    ratio = size / total_bytes
    bar_width = max(4, 570 * ratio)
    color = language_colors[name]
    language_svg += [
        text(34, y + 16, name, 16, "#f8fafc"),
        f'<rect x="190" y="{y}" width="570" height="18" rx="3" fill="#190012"/>',
        f'<rect x="190" y="{y}" width="{bar_width:.1f}" height="18" rx="3" fill="{color}"/>',
        text(860, y + 16, f"{ratio * 100:.1f}%", 15, "#67e8f9", 700, "end"),
    ]
language_svg.append("</svg>")

(ROOT / "assets" / "github-stats.svg").write_text("".join(stats_svg), encoding="utf-8")
(ROOT / "assets" / "language-stats.svg").write_text("".join(language_svg), encoding="utf-8")
